openapi: 3.0.0
servers:
  - description: NuBaDoo API
    url: 'https://api.nubadoo.com'
  - url: |
      https://8a58sxz9vc.execute-api.eu-west-1.amazonaws.com/production
    description: Demo server...
info:
  title: NuBaDoo API Documentation
  description: |
    *The NFT Travel Passposrt API powers the mechanism for interfacing with the backend system to manage resources in the NFT system. The API allows developers to access the platform's functionalities and incorporate the service into their own apps.*

    The NFT Travel Passort API's backbone is HTTP. The nature of our API is RESTful. It has a set of predictable resource URLs. It returns HTTP response codes to indicate errors or success. It also accepts JSON as an HTTP body payload and returns it.

    You can use your favorite HTTP/REST library for your programming language or an HTTP client like Postman or CURL to use the API.

    Happy coding **:-)**

    ## HTTP Response Status Codes
    HTTP response status codes show whether or not a particular HTTP request was completed successfully. Section 10 of RFC 2616 defines the status codes listed below. RFC 7231 contains an updated specification.
    Telephant API makes use of the following HTTP status codes, grouped into three classes:
    ### Successful Responses - 2XX
    #### 200 - OK
    The request has succeeded.
    #### 201 - Created
    As a result of the request's success, a new resource has been generated. This is the response that is normally sent in response to POST or some PUT queries.
    ### Client Error - 4XX

    #### 400 - Bad Request
    Due to incorrect syntax, the server was unable to understand the request.

    #### 401 - Unauthorized
    Authentication is required and has failed or has not yet been provided.

    #### 403 - Forbidden
    The server refuses to provide the requested resource because the client does not have access permissions to the resource; that is, it is unauthorized. Unlike 401, the server is aware of the client's identity.

    #### 404 - Not Found
    The requested resource was not found. The client is free to make additional requests.

    #### 405 - Method Not Allowed
    A GET request on a form that needs data to be presented via POST, or a PUT request on a read-only resource, for example, is not supported for the requested resource.
    ### Server Error - 5XX
    #### 500 - Internal Server Error
    The server has come upon a circumstance that it is unsure how to handle.  Our team will be reviewing the root cause of issues and resolving the problems as soon as possible.
  termsOfService: 'http://developer.nftpassport.travel/terms-of-service'
  version: '1.0'
  contact:
    name: Nubadoo Backend Team
    url: 'http://developer.nubadoo.com'
    email: api@nftpassport.travel
  x-logo:
    url: 'http://developer.nubadoo.com/logo.png'
    backgroundColor: '#212529'
paths:
  places:
    /places:
      get:
        tags:
          - Places
        description: Returns a list of Places.
        operationId: getPlaces
        responses:
          '200':
            description: Success
            content:
              application/json:
                examples:
                  getPlaces:
                    $ref: '#/components/examples/getPlaces'
          '400':
            $ref: '#/components/responses/400'
          '500':
            $ref: '#/components/responses/500'
      post:
        summary: Add a place.
        description: Create a new place.
        tags:
          - Places
        requestBody:
          description: Define the properties of the account to create.
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - accountName
                properties:
                  accountName:
                    type: string
                    minLength: 3
                    maxLength: 16
                    example: my-company
                    description: |
                      This field must be used as a reference on bank statements, 
                      and Telephant will use it to simplify the process.

                      **Note:** Only alphanumeric characters and hyphens as spaces are accepted 
                      in this field.
                      **Note:** The account id in the header will be ignored because 
                      the owner of the group account will be set to your username's phone number.
                    format: '^[a-z0-9-]{3,16}$'
                  description:
                    type: string
                    maxLength: 300
                    example: My Company (Pty) Ltd Airtime Account
        responses:
          '200':
            description: Success
            content:
              application/json:
                examples:
                  getPlaces:
                    $ref: '#/components/examples/getPlaces'
          '400':
            $ref: '#/components/responses/400'
          '500':
            $ref: '#/components/responses/500'
  'places/{place_id}':
    '/places/{place_id}':
      get:
        tags:
          - Places
        description: Returns a specific Place listing.
        operationId: getPlace
        parameters:
          - in: path
            name: place_id
            description: Provide the Place ID of a specific Place resource.
            schema:
              type: string
              format: uuid
            required: true
        responses:
          '200':
            description: Success
            content:
              application/json:
                examples:
                  getPlaces:
                    $ref: '#/components/examples/getPlaces'
          '400':
            $ref: '#/components/responses/400'
          '500':
            $ref: '#/components/responses/500'
      delete:
        summary: Delete Place.
        description: |
          Delete a specific place.
        tags:
          - Places
        parameters:
          - in: path
            name: place_id
            description: Provide the Place ID of a specific Place resource.
            schema:
              type: string
              format: uuid
            required: true
        responses:
          '410':
            description: Gone
            content:
              application/json:
                example:
                  code: 410
                  name: Gone
                  message: The ability to delete a group account has been removed.  In future a method for achieving this will be implemented.
      put:
        summary: Update place.
        description: |
          Update the details of a group account.

          **Note:** It is not possible to update your own username's account through the API 
          so an account_id must be provided in the header.
        tags:
          - Places
        requestBody:
          description: |
            Description...
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  owners:
                    type: string
                    pattern: '^(27)[0-9]{9}$'
                    example: 27821234567
                    description: |
                      In the South African phone number format, a user's unique mobile phone number.

                      You can assign multiple owners to a group account but only one per request.
                  description:
                    type: string
                    maxLength: 300
                    example: My Company (Pty) Ltd Airtime Account
                  businessType:
                    type: string
                    enum:
                      - private
                      - public
                      - ngo
                      - gov
        parameters:
          - in: path
            name: place_id
            description: Description
            schema:
              type: string
              format: uuid
            required: true
        responses:
          '201':
            description: Success
            content:
              application/json:
                example:
                  message: The group account was successfully updated.
          '500':
            $ref: '#/components/responses/500'
          4XX:
            description: BadRequestError
            content:
              application/json:
                examples:
                  ConflictError-1:
                    value:
                      code: 400
                      name: ConflictError
                      message: The user telephone number is already an owner on this account.
                  ConflictError-2:
                    value:
                      code: 400
                      name: ConflictError
                      message: Not a valid user's telphone number.
                  ConflictError-3:
                    value:
                      code: 400
                      name: ConflictError
                      message: No relevant fields to update were defined.
components:
  responses:
    '400':
      description: |
        Client error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 400
                description: |
                  Please review the documentation for [HTTP Response Status Codes](/#section/HTTP-Response-Status-Codes)
                  Possible values are:
                    - 400 - Bad Request
                    - 401 - Unauthorized
                    - 403 - Forbidden
                    - 404 - Not Found
                    - 405 - Method Not Allowed
              name:
                type: string
                example: BadRequest
                description: This value will always be returned as 'bumpy case'.
              message:
                type: string
                description: |
                  The message field will provide specific information as to the reason for the error.
                example: The account ID provided is not valid.
    '500':
      description: |
        Server error  
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 500
              name:
                type: string
                example: InternalServerError
              message:
                type: string
                example: We are sorry but something went wrong on our side.
  examples:
    getPlaces:
      value:
        page: 1
        total_pages: 1
        total_results: 3
        results:
          - _id: 60f57f3a6023f819ae7aa454
            accountName: '27829524031'
          - _id: 60ebd53e2f79311541618bc4
            accountName: MyCompany
            description: The account description for My Company
          - _id: 60ebd53e2f79311541618bc5
            accountName: My Company 2
            description: The account description for My Company 2
  schemas:
    place:
      type: object
      properties:
        id:
          type: integer
          format: int64
tags:
  - name: Places
    description: Places record the physical location where a beacon may be found.   It can be used to group various beacons to particular area.
  - name: Beacons
  - name: Badges
